version: '3.8'
services:
    app:
        build: .
        container_name: white-tail-merch-bot
        restart: always
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            BOT_OWNER: ${BOT_OWNER}
            BOT_PROVIDER_TOKEN: ${BOT_PROVIDER_TOKEN}
            MYSQL_JDBC_URL: jdbc:mysql://mysql:3306/
            MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
            MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        depends_on:
            - mysql
        volumes:
            - ./logs:/app/logs
    mysql:
        image: mysql:8.4
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
