spring:
    application:
        name: demoTGBot
    datasource:
        url: ${MYSQL_JDBC_URL:jdbc:mysql://localhost:3306/demo-tg-bot}
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 100
    jpa:
        hibernate:
            # TODO сделать ddl-auto: validate
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yml
    freemarker:
        template-loader-path: classpath:/templates/
        suffix: .ftl

bot:
    name: "White Tail"
    #    password: ${MYSQL_PASSWORD:} - example
    #    TODO вынести чувствительные данные в переменные окружения, Docker
    token: "7008020256:AAFiBEg786PHYvNvSIIwagT9IBV8sx1FHmw"
    owner: 214997124
    providerToken: 381764678:TEST:85689

logging:
    file:
        path: /var/log/shopbot.com/demo-tg-bot
        name: com.shopbot.demotgbot.DemoTgBot
