spring:
    application:
        name: whiteTailMerchBot
    datasource:
        url: ${MYSQL_JDBC_URL}${MYSQL_DATABASE_NAME}
        username: ${MYSQL_ROOT_USER}
        password: ${MYSQL_ROOT_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 100
    jpa:
        hibernate:
            # TODO сделать ddl-auto: validate
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yml
    freemarker:
        template-loader-path: classpath:/templates/
        suffix: .ftl

bot:
    name: "White Tail Merch Bot"
    token: ${BOT_TOKEN}
    owner: ${BOT_OWNER}
    providerToken: ${BOT_PROVIDER_TOKEN}
